### PR TITLE
Alice Frumin timer_js HW

### PR DESCRIPTION
**Pull request by alifrumin**
Comfort: 2
Completeness: 2

I got the start timer button to work... still have some stuff to work on with java script... the Context, Closure and Scope lecture was super helpful though.. I feel like Im making progress

### CODE REVIEW

**Comment by ebirving** [comment]
👍It looks like the mechanics of setInterval and clearInterval might be tripping you up on the stop functionality? The w3 schools article on clearInterval is a bit easier to read than the JS docs, and playing around with the Try it Yourself editor might help you unpack how it works... http://www.w3schools.com/jsref/met_win_clearinterval.asp

Let me know if you'd like to schedule a one-on-one tomorrow, either during lunch or after hours. No pressue -- just available if you're interested :-)

**Comment by alifrumin** [comment]
Thats probably a good idea... I could do during lunch tomorrow or after hours... just let me know whats easier for you.

Thank you :)

**Comment by ebirving** [comment]
Let's do 1:45 tomorrow. Are there any particular topics or assignments you'd like to review?

**Comment by alifrumin** [comment]
I think it'd be good to go over the js-Timer... I feel like im slowly getting a handle on this stuff but talking thru it one on one with you would speed things up. 1:45 it is.

**Comment by ebirving** [comment]
Perfect!

**Pull request closed without merging**
